MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '../models/pretrained_checkpoints/jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'vit_oafr'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  OCC_AUG: True
  ARC: 'OAFR'
  JPM: True
  SIE_CAMERA: False
  SIE_VIEW: False
  SIE_COE: 3.0


INPUT:
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.485, 0.456, 0.406]
  PIXEL_STD: [0.229, 0.224, 0.225]

DATASETS:
  NAMES: ('partial_reid')
  ROOT_DIR: ('/data1/wuyue/reid')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 160
  BASE_LR: 0.008
  LR2_bool: True
  LR_2: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  NEAREST_K: 5
  RECOVER_METHOD: 'soft_label'


TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: False
  WEIGHT: './logs/occ_reid_vit_oafr_224/train1/vit_oafrbest.pth'
#  WEIGHT: './logs/partial_reid_vit_oafr_224/train1nocamera/vit_oafrbest.pth'
  #WEIGHT: './logs/Market_0/vit_oafrbest.pth'
  #WEIGHT: './logs/Only1/Market_1/vit_oafrbest.pth'
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/partial_reid_vit_oafr_224/new/3'


