MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '../models/pretrained_checkpoints/swin_base_patch4_window7_224_22k.pth'
  METRIC_LOSS_TYPE: 'triplet'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'swin_oafr'
  ARC: 'OAFR'
  NO_MARGIN: True
  DEVICE_ID: ('1')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]


INPUT:
  #SIZE_TRAIN: [256, 128]
  #SIZE_TEST: [256, 128]
  SIZE_TRAIN: [224, 224]
  SIZE_TEST: [224, 224]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10


DATASETS:
  NAMES: ('occ_reid')
  ROOT_DIR: ('/data1/wuyue/reid/Occreid')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 0

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 100
  BASE_LR: 2e-03
  IMS_PER_BATCH: 128
  WARMUP_METHOD: 'linear'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 100
  LOG_PERIOD: 50
  WARMUP_EPOCHS: 5
  EVAL_PERIOD: 20
  WEIGHT_DECAY:  1e-8
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  NEAREST_K: 5
  RECOVER_METHOD: 'soft_label'
  
TEST:
  EVAL: True
  IMS_PER_BATCH: 128
  RE_RANKING: False
  #WEIGHT: './logs/occ_duke_swin_oafr/pad_test/swin_oafr06160243_100.pth'
  WEIGHT: './logs/Market_swin_oafr/swin_oafr07222000_200.pth'
  #WEIGHT: './logs/Market_swin_oafr_256/padding/swin_oafr08080007_200.pth'
  VISUALIZE: False
  VISUAL_MODE: "all"
  VISUAL_DIR: './logs/occ_reid_swin_oafr/visual_all/visual_weights'
  LOCAL: True
  VISUAL_FEAT_RECOVERY: False
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'

OUTPUT_DIR: './logs/occ_reid_swin_oafr_256'
